export const types = {
    // Sync
    START_FETCHING: 'START_FETCHING',
    STOP_FETCHING: 'STOP_FETCHING',
    FILL_STARSHIPS: 'FILL_STARSHIPS',
    // Async
    FETCH_STARSHIPS_ASYNC: 'FETCH_STARSHIPS_ASYNC',
};
